name: todohuy
description: A new Flutter project for TodoHuy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Firebase Core & Backend
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  google_sign_in: ^6.2.2
  
  # Routing
  go_router: ^18.0.1
  
  # Utilities
  intl: ^0.20.3
  uuid: ^4.2.1
  connectivity_plus: ^7.3.1
  url_launcher: ^6.3.1
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  open_filex: ^4.7.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
