// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCsIqkx3mfofNNkKGue1T82CByzdlylo',
    appId: '1:154847841204:web:b283fe82edaf9af18680e1',
    messagingSenderId: '154847841204',
    projectId: 'todohuy-flutter',
    authDomain: 'todohuy-flutter.firebaseapp.com',
    storageBucket: 'todohuy-flutter.firebasestorage.app',
    measurementId: 'G-JZG8F1XTVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuuFmu5GJg5_9C_hHAj9-qLpD_n8StQgk',
    appId: '1:154847841204:android:28b101d1957d281f8680e1',
    messagingSenderId: '154847841204',
    projectId: 'todohuy-flutter',
    storageBucket: 'todohuy-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJdPhiT4Dv6pUCg-lgoX-0T_4wyS_LHE',
    appId: '1:154847841204:ios:a8540fc06c32ed558680e1',
    messagingSenderId: '154847841204',
    projectId: 'todohuy-flutter',
    storageBucket: 'todohuy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todohuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJdPhiT4Dv6pUCg-lgoX-0T_4wyS_LHE',
    appId: '1:154847841204:ios:a8540fc06c32ed558680e1',
    messagingSenderId: '154847841204',
    projectId: 'todohuy-flutter',
    storageBucket: 'todohuy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.todohuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhCsIqkx3mfofNNkKGue1T82CByzdlylo',
    appId: '1:154847841204:web:42d2ab274b3ffaaa8680e1',
    messagingSenderId: '154847841204',
    projectId: 'todohuy-flutter',
    authDomain: 'todohuy-flutter.firebaseapp.com',
    storageBucket: 'todohuy-flutter.firebasestorage.app',
    measurementId: 'G-VM7NDTWHM6',
  );
}
